import React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
	container: {
		display: "flex",
		flexDirection: "column",
		justifyContent: "flex-start",
		minHeight: "100vh",
		backgroundColor: "#f0f0f0",
		padding: "20px",
	},
	todoApp: {
		backgroundColor: "#fff",
		padding: "20px",
		borderRadius: "8px",
		boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
		width: "100%",
		maxWidth: "1200px",
		margin: "0 auto",
		marginTop: "60px",
	},
	toolbar: {
		display: "flex",
		justifyContent: "flex-end",
		gap: "10px",
		marginBottom: "20px",
	},
	button: {
		padding: "10px 15px",
		backgroundColor: "#4CAF50",
		color: "#fff",
		border: "none",
		borderRadius: "4px",
		cursor: "pointer",
		transition: "background-color 0.3s ease",
	},
	ButtonHover: {
		backgroundColor: "#45a049",
	},
	buttonContainer: {
		display: "flex",
		gap: "10px",
		alignItems: "center",
	},
	buttonDanger: {
		backgroundColor: "#e74c3c",
	},
	inputContainer: {
		display: "flex",
		marginBottom: "20px",
		width: "100%",
		gap: "10px",
	},
	input: {
		flex: 1,
		padding: "10px",
		fontSize: "16px",
		border: "1px solid #ccc",
		borderRadius: "4px",
		outline: "none",
		transition: "border-color 0.3s ease",
	},
	inputFocus: {
		borderColor: "#4CAF50",
	},
	taskList: {
		listStyle: "none",
		padding: 0,
		margin: 0,
	},
	task: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		padding: "10px",
		marginBottom: "10px",
		backgroundColor: "#f9f9f9",
		borderRadius: "4px",
		width: "100%",
		boxSizing: "border-box",
	},
	footer: {
		backgroundColor: "#4CAF50",
		color: "#fff",
		padding: "10px",
		textAlign: "center",
		width: "100%",
		position: "fixed",
		left: 0,
		right: 0,
		bottom: 0,
		zIndex: 1000,
		borderRadius: "8px",
		fontWeight: "bolder",
	},
	header: {
		backgroundColor: "#4CAF50",
		position: "fixed",
		top: 0,
		left: 0,
		right: 0,
		color: "#fff",
		padding: "10px",
		borderRadius: "8px",
		width: "100%",
		textAlign: "center",
		fontSize: "24px",
		zIndex: 1000,
		fontWeight: "bold",
	},
};
